modLoader = "javafml"
loaderVersion = "[41,)"
license = "the Unlicense"

[[mods]]
modId = "ciboptout"
version = "${version}"
displayName = "CIB Optout"
authors = "F53"
description = '''
optout for lame servers that dont like cardinal ice boats
'''
#logoFile = ""

[[dependencies.ciboptout]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.ciboptout]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.ciboptout]]
modId = "architectury"
mandatory = true
versionRange = "[5.7.28,)"
ordering = "AFTER"
side = "SERVER"